### ISSUE TITLE
Replace sentinel font reference to the google alternative

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-calendar-components#3]
Sentinel font is very likely to be going away; let's make the switch to google fonts - Domine

https://fonts.google.com/specimen/Domine

Check and make sure the font sizes don't need to be adjusted to match their size/styles before.
We can include this google font reference in the template for a row or tile, whichever ones use this font.

**Comment by masterqwerty** [comment]
I added the Domine font and adjusted some of the font sizes accordingly. There should be a pull request now.
