### ISSUE TITLE
Add Minimalist Horizontal Tile component

### ISSUE THREAD

**Issue by katrialesser** [byuweb/byu-calendar-components#4]
Let's add a quick simple component and display type for this new tile format:
https://byu.app.box.com/file/299067743269  - scroll down a couple pages, it's a block on the left. Don't worry about the Calendar block title style or line to the right,
![image](https://user-images.githubusercontent.com/12898896/41941267-b6d5e950-7958-11e8-97e6-0304bda8ade4.png)
Let's have the royal background, as seen in the mockup, but allow a navy-background option by adding that class to the byu-minimal-tile element.

Colors:
https://byu.app.box.com/file/291987058104
brand.byu.edu/guidelines/color/

**Comment by katrialesser** [comment]
this component could start as a copy of one of the calendar-tile components.

**Comment by masterqwerty** [comment]
Component has now been merged to the master branch in the form of the byu-calendar-minimal-tile.
